databases:
  - name: postgres
    ipAllowList: []
    databaseName: stock_api
    user: stock_api

services:
  - type: web
    name: stock_api
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: SECRET_KEY_BASE
        sync: true
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false