default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_USER_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  url: <%= ENV['DATABASE_URL'] %>
development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
